---
- name: Ensure TLS directory exists
  ansible.builtin.file:
    path: "{{ hashivault_deploy_tls_cert_file | dirname }}"
    state: directory
    owner: "{{ hashivault_deploy_user }}"
    group: "{{ hashivault_deploy_group }}"
    mode: '0750'

- name: Set TLS filenames for current node
  ansible.builtin.set_fact:
    tls_cert_src: >-
      {{
        (hashivault_deploy_tls_wildcard | default(false))
        | ternary(
          hashivault_deploy_tls_wildcard_name ~ ".pem",
          inventory_hostname ~ ".pem"
        )
      }}
    tls_key_src: >-
      {{
        (hashivault_deploy_tls_wildcard | default(false))
        | ternary(
          hashivault_deploy_tls_wildcard_name ~ ".key",
          inventory_hostname ~ ".key"
        )
      }}

- name: Copy Vault TLS certificate file
  copy:
    src: "{{ tls_cert_src }}"
    dest: "{{ hashivault_deploy_tls_cert_file }}"
    owner: "{{ hashivault_deploy_user }}"
    group: "{{ hashivault_deploy_group }}"
    mode: '0640'
  when:
    - hashivault_deploy_tls_cert_file is defined
    - hashivault_deploy_tls_cert_file | length > 0
    - lookup('file', tls_cert_src, errors='ignore') is not none

- name: Copy Vault TLS private key file
  copy:
    src: "{{ tls_key_src }}"
    dest: "{{ hashivault_deploy_tls_key_file }}"
    owner: "{{ hashivault_deploy_user }}"
    group: "{{ hashivault_deploy_group }}"
    mode: '0600'
  when:
    - hashivault_deploy_tls_key_file is defined
    - hashivault_deploy_tls_key_file | length > 0
    - lookup('file', tls_key_src, errors='ignore') is not none
