---
- name: Ensure required packages are installed
  ansible.builtin.apt:
   update_cache: true
   state: present
   name:
    - lsb-release
    - gpg
    - wget
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed (RedHat)
  ansible.builtin.dnf:
   name:
    - lsb_release
    - gpg
    - wget
   state: present
   update_cache: true
  become: true
  when: ansible_os_family == "RedHat"
