# SPDX-License-Identifier: MIT-0
---
# tasks file for hashivault_deploy
- name: Install required packages for Vault
  ansible.builtin.import_tasks:
    file: install_deps.yml
- name: Install Vault
  ansible.builtin.import_tasks:
    file: install_vault.yml
