---
- block:
    - name: Load unseal keys from controller file
      ansible.builtin.slurp:
        src: "{{ hashivault_deploy_secret }}"
      register: hashivault_deploy_unseal_file
      delegate_to: localhost
      become: true

    - name: Unseal Vault nodes
      ansible.builtin.command: vault operator unseal {{ item }}
      loop: "{{ hashivault_deploy_unseal_data.unseal_keys_b64[:hashivault_deploy_shamir_key_threshold] }}"
      environment:
        VAULT_ADDR: "{{ hashivault_deploy_vault_addr }}"
      register: hashivault_deploy_unseal_result
      retries: 5
      delay: 5
      until: hashivault_deploy_unseal_result is succeeded
      changed_when: hashivault_deploy_unseal_result is succeeded
      failed_when: hashivault_deploy_unseal_result is failed
  vars:
    hashivault_deploy_unseal_data: "{{ hashivault_deploy_unseal_file.content | b64decode | from_json }}"
