- name: Unseal Vault nodes if token file exists
  vars:
    hashivault_deploy_unseal_data: "{{ (hashivault_deploy_token_file.content | b64decode | from_json).unseal_keys_b64 }}"
  when: hashivault_deploy_token is file
  block:
    - name: Load unseal keys from controller file
      ansible.builtin.slurp:
        src: "{{ hashivault_deploy_token }}"
      register: hashivault_deploy_token_file
      delegate_to: localhost
      become: true
      no_log: true

    - name: Unseal Vault nodes via API
      ansible.builtin.uri:
        url: "{{ hashivault_deploy_vault_addr }}/v1/sys/unseal"
        method: POST
        body_format: json
        body:
          key: "{{ item }}"
        return_content: true
        status_code: 200, 204
      loop: "{{ hashivault_deploy_unseal_data[:hashivault_deploy_shamir_key_threshold] }}"
      register: hashivault_deploy_unseal_result
      retries: 5
      delay: 5
      until: hashivault_deploy_unseal_result.status in [200, 204]
      changed_when: hashivault_deploy_unseal_result is succeeded
      failed_when: hashivault_deploy_unseal_result is failed
      no_log: true

- name: Skip unsealing if token file not found
  ansible.builtin.debug:
    msg: "Token file '{{ hashivault_deploy_token }}' not found, skipping unsealing."
  when: hashivault_deploy_token is not file
