---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Validate hashivault_deploy variables
      ansible.builtin.import_tasks: ../../tasks/validate_vars.yml

  roles:
    - role: hashivault_deploy
