---
- name: Verify Vault installation and runtime
  hosts: all
  gather_facts: true
  tasks:
    # -----------------------------
    # Binary & Directories
    # -----------------------------
    - name: Vault binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/vault
      register: vault_binary

    - name: Assert Vault is installed
      ansible.builtin.assert:
        that:
          - vault_binary.stat.exists

    - name: Check Vault config directory exists
      ansible.builtin.stat:
        path: "{{ hashivault_deploy_config_dir }}"
      register: config_dir

    - name: Assert config directory exists
      ansible.builtin.assert:
        that:
          - config_dir.stat.exists

    - name: Check Vault data directory exists
      ansible.builtin.stat:
        path: "{{ hashivault_deploy_data_dir }}"
      register: data_dir

    - name: Assert data directory exists
      ansible.builtin.assert:
        that:
          - data_dir.stat.exists

    - name: Check Vault token file exists
      ansible.builtin.stat:
        path: "{{ hashivault_deploy_token }}"
      register: token_file

    - name: Assert token file exists
      ansible.builtin.assert:
        that:
          - token_file.stat.exists

    # -----------------------------
    # Service & Ports
    # -----------------------------
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert Vault service is active
      ansible.builtin.assert:
        that:
          - "'vault' in services"
          - services['vault'].state == 'running'
          - services['vault'].status == 'enabled'

    - name: Check Vault TCP ports
      ansible.builtin.wait_for:
        host: "{{ hashivault_deploy_vault_ip }}"
        port: "{{ item }}"
        timeout: 5
      loop:
        - "{{ hashivault_deploy_vault_port }}"
        - "{{ hashivault_deploy_vault_cluster_port }}"
