#SPDX-License-Identifier: MIT-0
---
# handlers file for backup
- name: Remove temporary backup file on Ansible controller
  tags: [cleanup]
  when: not direct_transfer | bool
  ansible.builtin.file:
    path: "{{ non_direct_transfer_tmp_path }}/{{ backup_full_filename }}"
    state: absent

# -----------------------------
#  Cleanup on Router
# -----------------------------
- name: Clean up backup file on MikroTik
  tags: [cleanup]
  routeros_command:
    commands:
      - /file remove {{ backup_full_filename }}
