# SPDX-License-Identifier: MIT-0
---
# tasks file for backup

- name: Generate timestamp
  set_fact:
    backup_timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Define backup filename without extension
  set_fact:
    backup_filename: "{{ inventory_hostname }}.{{ backup_timestamp }}"

- name: Define backup file extension
  set_fact:
    backup_extension: "{{ 'backup' if backup_format == 'backup' else 'rsc' }}"

- name: Define full backup file name with extension
  set_fact:
    backup_full_filename: "{{ backup_filename }}.{{ backup_extension }}"

- name: Create backup file on MikroTik
  routeros_command:
    commands:
      - >-
        {% if backup_format == 'backup' %}
        /system/backup/save encryption=aes-sha256 password={{ backup_pass }} name={{ backup_filename }}
        {% else %}
        /export file={{ backup_filename }}
        {% endif %}

# -----------------------------
#  Direct Transfer (MikroTik → Remote)
# -----------------------------
- name: Upload backup file to remote destination (MikroTik push)
  when: direct_transfer | bool
  routeros_command:
    commands:
      - >-
        /tool fetch upload=yes mode=sftp ascii=no
        src-path="{{ backup_full_filename }}"
        dst-path="{{ remote_backup_path }}/{{ backup_full_filename }}"
        address={{ remote_backup_host }}
        port={{ remote_backup_port }}
        user={{ remote_backup_user }}
        password={{ remote_backup_password }}

# -----------------------------
#  Indirect Transfer (MikroTik → Ansible → Remote)
# -----------------------------
- name: Fetch backup file from MikroTik to Ansible controller
  when: not direct_transfer | bool
  ansible.netcommon.net_get:
    src: "{{ backup_full_filename }}"
    dest: "{{ non_direct_transfer_tmp_path }}/{{ backup_full_filename }}"


- name: Upload backup from Ansible controller to remote destination via SFTP (SSH key)
  when:
    - not direct_transfer | bool
    - remote_backup_ssh_key is defined
  ansible.builtin.shell:
    cmd: >
      echo "put {{ non_direct_transfer_tmp_path }}/{{ backup_full_filename }} {{ remote_backup_path }}/{{ backup_full_filename }}" |
      sftp -i {{ remote_backup_ssh_key }} -oStrictHostKeyChecking=no -P {{ remote_backup_port }}
      {{ remote_backup_user }}@{{ remote_backup_host }}
  register: sftp_upload_ssh
  changed_when: sftp_upload_ssh.rc == 0

- name: Upload backup from Ansible controller to remote destination via SFTP (password fallback)
  when:
    - not direct_transfer | bool
    - remote_backup_ssh_key is not defined
  ansible.builtin.shell:
    cmd: >
      echo "put {{ non_direct_transfer_tmp_path }}/{{ backup_full_filename }} {{ remote_backup_path }}/{{ backup_full_filename }}" |
      sftp -oStrictHostKeyChecking=no -P {{ remote_backup_port }}
      {{ remote_backup_user }}@{{ remote_backup_host }}
  register: sftp_upload_pw
  changed_when: sftp_upload_pw.rc == 0

- name: Remove temporary backup file from Ansible controller
  when: not direct_transfer | bool
  ansible.builtin.file:
    path: "{{ non_direct_transfer_tmp_path }}/{{ backup_full_filename }}"
    state: absent

# -----------------------------
#  Cleanup on Router
# -----------------------------
- name: Clean up backup file on MikroTik
  tags: [cleanup]
  routeros_command:
    commands:
      - /file remove {{ backup_full_filename }}
