# SPDX-License-Identifier: MIT-0
---
- name: Verify public keys
  import_tasks: verify_pubkeys.yml
  run_once: true
  delegate_to: localhost

- name: Fetch userlist from MikroTik
  import_tasks: fetch_mikrotik_users.yml

- name: Verify MikroTik users
  import_tasks: verify_mikrotik_users.yml

- name: Setup upload list based on verifications
  import_tasks: setup_upload_list.yml

- name: Flush ssh keys if allowed
  import_tasks: flush_ssh_pubkeys.yml

- name: Upload public keys to MikroTik
  import_tasks: upload_pubkeys.yml

- name: Import public keys on MikroTik
  import_tasks: import_pubkeys.yml
