#SPDX-License-Identifier: MIT-0
---
- name: Copy public key to MikroTik device
  ansible.netcommon.net_put:
    src: "{{ role_path }}/files/{{ item.pubkey_file }}"
    dest: "{{ item.name }}.pub"
  loop: "{{ mikrotik_ssh_users }}"

- name: Import public key from uploaded file
  community.routeros.command:
    commands:
      - "/user ssh-keys import public-key-file={{ item.pubkey_file }} user={{ item.name }}"
  loop: "{{ mikrotik_ssh_users }}"
  