# SPDX-License-Identifier: MIT-0
---

- name: Validate inputs and check prerequisites
  ansible.builtin.include_tasks: validate.yml

- name: Set up backup metadata
  ansible.builtin.include_tasks: set_backup_facts.yml

- name: Create backup file on MikroTik
  ansible.builtin.include_tasks: create_backup.yml

- name: Transfer backup (direct or indirect)
  ansible.builtin.include_tasks: "{{ 'transfer_direct.yml' if direct_transfer | bool else 'transfer_indirect.yml' }}"
