
# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  role_name: backup
  author: Paweł Wołochow
  description: MikroTik backup automation via Ansible (direct & indirect SFTP).
  license: MIT-0
  min_ansible_version: "2.14"
  platforms:
    - name: RouterOS
      versions:
        - all
  galaxy_tags:
    - mikrotik
    - routeros
    - backup
    - sftp
    - automation
    - network
    - ssh
    - ansible

dependencies: []
