# SPDX-License-Identifier: MIT-0
# handlers file for hashivault_deploy
---
- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reexec
  become: true
  changed_when: false
  # noqa: command-instead-of-module

- name: Restart Vault
  ansible.builtin.service:
    name: vault
    state: restarted
  become: true

- name: Reload environment
  ansible.builtin.shell: |
    export VAULT_ADDR={{ 'https' if hashivault_deploy_tls_enabled else 'http' }}://{{ ansible_default_ipv4.address }}:8200
  when: ansible_connection != 'local'
