# SPDX-License-Identifier: MIT-0
---
backup_format: backup           # 'export' or 'backup' mikrotik formats

# Whether to use direct SFTP from MikroTik to the remote server
direct_transfer: false

# Optional if backup_format == 'backup' | Sets password and enables encryption on backup file created by Mikrotik
#encrypt_pass: CHANGE_ME


############################################
# Remote destination settings (both modes)
############################################
remote_backup_user: CHANGE_ME
remote_backup_host: backup.example.com
remote_backup_path: /example/path/to/directory
remote_backup_port: 22


############################################
# Settings used only in non-direct transfer
# MikroTik → Ansible Controller → Remote
############################################
# Temporary location on the controller to store backup file
non_direct_transfer_tmp_path: "/tmp" 

###########################################
# Used only in direct transfer (MikroTik pushes file to remote)
############################################
# Only needed if MikroTik cannot use SSH key-based auth
# remote_backup_password: CHANGE_ME