# SPDX-License-Identifier: MIT-0
---
backup_format: backup           # 'export' or 'backup'
direct_transfer: false
non_direct_transfer_tmp_path: "/tmp" # path where ansible controller stores backups from mikrotiks during execution         # Not available when export type used
#backup_pass: CHANGE_ME          # Optional if backup_format == 'backup' | Sets password on backup file created on mikrotik
# remote location settings
remote_backup_user: CHANGE_ME

#remote_backup_password: CHANGE_ME # Set only if your mikrotik can't use SSH key-based auth to backup host.
remote_backup_host: backup.example.com
remote_backup_path: /example/path/to/directory
remote_backup_port: 22