name: Molecule Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - debian:11
          - debian:12
          - debian:bookworm
          - ubuntu:22.04
          - ubuntu:23.04
          - fedora:41
          - fedora:42
          - centos:8
          - centos:9
          - amazonlinux:2
          - amazonlinux:latest
    defaults:
      run:
        working-directory: roles/hashivault_deploy
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ matrix.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Molecule dependencies
        run: pip install molecule[docker] ansible-lint yamllint

      - name: Update Molecule image for current OS
        run: |
          sed -i "s|image: .*|image: ${{ matrix.os }}|" molecule/default/molecule.yml

      - name: Run Molecule tests
        run: molecule test
